name: Leaked Secrets Scan
on: 
  pull_request:
  workflow_dispatch:
  repository_dispatch:
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@cbf299aa772f657534cd630442ddfb2f38a0f3d0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
